name: release-workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World!!'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet1:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
  
  get_current_version:
    runs-on: ubuntu-latest
    needs: greet1
    steps:
      - name: checkout-repo-content
        uses: actions/checkout@v2
      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: execute-script
        run: |
          output=$(python3 release_utils.py --release_type patch)
          echo '::set-output name=next_version::$output'
          echo $next_version
    outputs:
      next_version: ${{ steps.execute-script.outputs.next_version }}

  # checkout a new branch release-x.y.z
  checkout_branch:
    runs-on: ubuntu-latest
    needs: get_current_version
    steps:
      - name: checkout-new-release-branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PD_TOKEN }}
        with:
          branch: release-v${{ needs.get_current_version.outputs.next_version }}
