name: New Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Person to greet'
        default: 'World!!'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet1:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
  
  get_current_version:
    runs-on: ubuntu-latest
    needs: greet1
    outputs:
      next_version: ${{ steps.step1.outputs.next_version }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: execute script
        run: |
          output=$(python3 release_utils.py --release_type patch)
          echo "::set-output name=next_version::$output"

  # checkout a new branch release_x.y.z
  checkout_branch:
    runs-on: ubuntu-latest
    needs: get_current_version
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - with:
          branch: release-v${{ needs.get_current_version.outputs.next_version }}
